// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "pcm/proto/v1/pcm_service.proto" (package "Pcm", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Bridge } from "./pcm_service";
import type { ProvReq } from "./pcm_service";
import type { ResetReq } from "./pcm_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Msg } from "../../../ciot/proto/v2/msg";
import type { BridgeReq } from "./pcm_service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service Pcm.Bridge
 */
export interface IBridgeClient {
    /**
     * @generated from protobuf rpc: SendReq
     */
    sendReq(input: BridgeReq, options?: RpcOptions): UnaryCall<BridgeReq, Msg>;
    /**
     * @generated from protobuf rpc: Reset
     */
    reset(input: ResetReq, options?: RpcOptions): UnaryCall<ResetReq, Msg>;
    /**
     * @generated from protobuf rpc: Prov
     */
    prov(input: ProvReq, options?: RpcOptions): UnaryCall<ProvReq, Msg>;
}
/**
 * @generated from protobuf service Pcm.Bridge
 */
export class BridgeClient implements IBridgeClient, ServiceInfo {
    typeName = Bridge.typeName;
    methods = Bridge.methods;
    options = Bridge.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: SendReq
     */
    sendReq(input: BridgeReq, options?: RpcOptions): UnaryCall<BridgeReq, Msg> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<BridgeReq, Msg>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Reset
     */
    reset(input: ResetReq, options?: RpcOptions): UnaryCall<ResetReq, Msg> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ResetReq, Msg>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Prov
     */
    prov(input: ProvReq, options?: RpcOptions): UnaryCall<ProvReq, Msg> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ProvReq, Msg>("unary", this._transport, method, opt, input);
    }
}
