// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "pcm/proto/v1/pcm_service.proto" (package "Pcm", syntax proto3)
// tslint:disable
import { Msg } from "../../../ciot/proto/v2/msg";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { AckType } from "./pcm";
import { ReqType } from "./pcm";
/**
 * @generated from protobuf message Pcm.BridgeReq
 */
export interface BridgeReq {
    /**
     * @generated from protobuf field: Pcm.ReqType type = 1
     */
    type: ReqType; // Type of the request
    /**
     * @generated from protobuf field: string ble_hdr_mac = 2
     */
    bleHdrMac: string; // Target device ble hedro mac address
    /**
     * @generated from protobuf field: string ble_original_mac = 3
     */
    bleOriginalMac: string; // Target device ble original mac address
    /**
     * @generated from protobuf field: string content = 4
     */
    content: string; // Request content
    /**
     * @generated from protobuf field: uint32 timeout = 5
     */
    timeout: number; // Request timeout
}
/**
 * @generated from protobuf message Pcm.BridgeAck
 */
export interface BridgeAck {
    /**
     * @generated from protobuf field: Pcm.AckType type = 1
     */
    type: AckType; // Type of the acknowledgement
    /**
     * @generated from protobuf field: string ble_hdr_mac = 2
     */
    bleHdrMac: string; // Target device ble hedro mac address
    /**
     * @generated from protobuf field: string ble_original_mac = 3
     */
    bleOriginalMac: string; // Target device ble original mac address
    /**
     * @generated from protobuf field: string payload = 4
     */
    payload: string; // Payload which generates the ack
    /**
     * @generated from protobuf field: int32 rssi = 5
     */
    rssi: number; // Device signal strength
}
/**
 * @generated from protobuf message Pcm.ResetReq
 */
export interface ResetReq {
    /**
     * @generated from protobuf field: string ble_hdr_mac = 1
     */
    bleHdrMac: string; // Target device ble hedro mac address
    /**
     * @generated from protobuf field: string ble_original_mac = 2
     */
    bleOriginalMac: string; // Target device ble original mac address
    /**
     * @generated from protobuf field: uint32 timeout = 3
     */
    timeout: number; // Request timeout
}
/**
 * @generated from protobuf message Pcm.ProvReq
 */
export interface ProvReq {
    /**
     * @generated from protobuf field: string ble_hdr_mac = 1
     */
    bleHdrMac: string; // Target device ble hedro mac address
    /**
     * @generated from protobuf field: string ble_original_mac = 2
     */
    bleOriginalMac: string; // Target device ble original mac address
    /**
     * @generated from protobuf field: uint32 timeout = 3
     */
    timeout: number; // Request timeout
}
// @generated message type with reflection information, may provide speed optimized methods
class BridgeReq$Type extends MessageType<BridgeReq> {
    constructor() {
        super("Pcm.BridgeReq", [
            { no: 1, name: "type", kind: "enum", T: () => ["Pcm.ReqType", ReqType, "REQ_TYPE_"] },
            { no: 2, name: "ble_hdr_mac", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "ble_original_mac", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "timeout", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<BridgeReq>): BridgeReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.type = 0;
        message.bleHdrMac = "";
        message.bleOriginalMac = "";
        message.content = "";
        message.timeout = 0;
        if (value !== undefined)
            reflectionMergePartial<BridgeReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BridgeReq): BridgeReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* Pcm.ReqType type */ 1:
                    message.type = reader.int32();
                    break;
                case /* string ble_hdr_mac */ 2:
                    message.bleHdrMac = reader.string();
                    break;
                case /* string ble_original_mac */ 3:
                    message.bleOriginalMac = reader.string();
                    break;
                case /* string content */ 4:
                    message.content = reader.string();
                    break;
                case /* uint32 timeout */ 5:
                    message.timeout = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BridgeReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* Pcm.ReqType type = 1; */
        if (message.type !== 0)
            writer.tag(1, WireType.Varint).int32(message.type);
        /* string ble_hdr_mac = 2; */
        if (message.bleHdrMac !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.bleHdrMac);
        /* string ble_original_mac = 3; */
        if (message.bleOriginalMac !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.bleOriginalMac);
        /* string content = 4; */
        if (message.content !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.content);
        /* uint32 timeout = 5; */
        if (message.timeout !== 0)
            writer.tag(5, WireType.Varint).uint32(message.timeout);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Pcm.BridgeReq
 */
export const BridgeReq = new BridgeReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BridgeAck$Type extends MessageType<BridgeAck> {
    constructor() {
        super("Pcm.BridgeAck", [
            { no: 1, name: "type", kind: "enum", T: () => ["Pcm.AckType", AckType, "ACK_TYPE_"] },
            { no: 2, name: "ble_hdr_mac", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "ble_original_mac", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "payload", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "rssi", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<BridgeAck>): BridgeAck {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.type = 0;
        message.bleHdrMac = "";
        message.bleOriginalMac = "";
        message.payload = "";
        message.rssi = 0;
        if (value !== undefined)
            reflectionMergePartial<BridgeAck>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BridgeAck): BridgeAck {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* Pcm.AckType type */ 1:
                    message.type = reader.int32();
                    break;
                case /* string ble_hdr_mac */ 2:
                    message.bleHdrMac = reader.string();
                    break;
                case /* string ble_original_mac */ 3:
                    message.bleOriginalMac = reader.string();
                    break;
                case /* string payload */ 4:
                    message.payload = reader.string();
                    break;
                case /* int32 rssi */ 5:
                    message.rssi = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BridgeAck, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* Pcm.AckType type = 1; */
        if (message.type !== 0)
            writer.tag(1, WireType.Varint).int32(message.type);
        /* string ble_hdr_mac = 2; */
        if (message.bleHdrMac !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.bleHdrMac);
        /* string ble_original_mac = 3; */
        if (message.bleOriginalMac !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.bleOriginalMac);
        /* string payload = 4; */
        if (message.payload !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.payload);
        /* int32 rssi = 5; */
        if (message.rssi !== 0)
            writer.tag(5, WireType.Varint).int32(message.rssi);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Pcm.BridgeAck
 */
export const BridgeAck = new BridgeAck$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ResetReq$Type extends MessageType<ResetReq> {
    constructor() {
        super("Pcm.ResetReq", [
            { no: 1, name: "ble_hdr_mac", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "ble_original_mac", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "timeout", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<ResetReq>): ResetReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.bleHdrMac = "";
        message.bleOriginalMac = "";
        message.timeout = 0;
        if (value !== undefined)
            reflectionMergePartial<ResetReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ResetReq): ResetReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string ble_hdr_mac */ 1:
                    message.bleHdrMac = reader.string();
                    break;
                case /* string ble_original_mac */ 2:
                    message.bleOriginalMac = reader.string();
                    break;
                case /* uint32 timeout */ 3:
                    message.timeout = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ResetReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string ble_hdr_mac = 1; */
        if (message.bleHdrMac !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.bleHdrMac);
        /* string ble_original_mac = 2; */
        if (message.bleOriginalMac !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.bleOriginalMac);
        /* uint32 timeout = 3; */
        if (message.timeout !== 0)
            writer.tag(3, WireType.Varint).uint32(message.timeout);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Pcm.ResetReq
 */
export const ResetReq = new ResetReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProvReq$Type extends MessageType<ProvReq> {
    constructor() {
        super("Pcm.ProvReq", [
            { no: 1, name: "ble_hdr_mac", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "ble_original_mac", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "timeout", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<ProvReq>): ProvReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.bleHdrMac = "";
        message.bleOriginalMac = "";
        message.timeout = 0;
        if (value !== undefined)
            reflectionMergePartial<ProvReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProvReq): ProvReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string ble_hdr_mac */ 1:
                    message.bleHdrMac = reader.string();
                    break;
                case /* string ble_original_mac */ 2:
                    message.bleOriginalMac = reader.string();
                    break;
                case /* uint32 timeout */ 3:
                    message.timeout = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProvReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string ble_hdr_mac = 1; */
        if (message.bleHdrMac !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.bleHdrMac);
        /* string ble_original_mac = 2; */
        if (message.bleOriginalMac !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.bleOriginalMac);
        /* uint32 timeout = 3; */
        if (message.timeout !== 0)
            writer.tag(3, WireType.Varint).uint32(message.timeout);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Pcm.ProvReq
 */
export const ProvReq = new ProvReq$Type();
/**
 * @generated ServiceType for protobuf service Pcm.Bridge
 */
export const Bridge = new ServiceType("Pcm.Bridge", [
    { name: "SendReq", options: {}, I: BridgeReq, O: Msg },
    { name: "Reset", options: {}, I: ResetReq, O: Msg },
    { name: "Prov", options: {}, I: ProvReq, O: Msg }
]);
